const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

// Global Arrays & Defaults
if (!global.badwords) global.badwords = [];
if (!global.ignorelist) global.ignorelist = [];
if (!global.sudousers) global.sudousers = [];
if (!global.allowedCountries) global.allowedCountries = ['91']; 

// Global Bot Custom Strings
if (!global.botConfigText) {
    global.botConfigText = {
        anticallMsg: "🚫 Calls are not allowed! You have been automatically blocked.",
        contextLink: "https://github.com/nicholas-pp8/EnigmaD20",
        menuImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe",
        watermark: "Generated by Enigma D20",
        stickerPack: "Enigma Pack",
        stickerAuthor: "Rohan Sharma",
        statusEmoji: "🔥",
        timezone: "Asia/Kolkata",
        mode: "public"
    };
}

async function handleOwnerCommands(sock, from, msg, args, command, isOwner) {
    if (!isOwner) return await sock.sendMessage(from, { text: "❌ *Access Denied!* Only the bot owner can use this." }, { quoted: msg });

    const value = args[0]?.toLowerCase();
    const textArg = args.join(' ');

    // 1. TOGGLE SWITCHES (On/Off)
    const toggleSettings = ['alwaysonline', 'antibug', 'anticall', 'antidelete', 'antideletestatus', 'antiedit', 'antiviewonce', 'autobio', 'autoblock', 'autoreact', 'autoreactstatus', 'autoread', 'autorecord', 'autorecordtyping', 'autotype', 'autoviewstatus', 'chatbot'];
    
    if (toggleSettings.includes(command)) {
        if (!value || (value !== 'on' && value !== 'off')) return await sock.sendMessage(from, { text: `⚠️ Please use *on* or *off*!\n*Example:* .${command} on` }, { quoted: msg });
        global.settings[command] = (value === 'on');
        if (command === 'alwaysonline') await sock.sendPresenceUpdate(value === 'on' ? 'available' : 'unavailable');
        return await sock.sendMessage(from, { text: `✅ *${command.toUpperCase()}* is now turned *${value.toUpperCase()}*.` }, { quoted: msg });
    }

    switch (command) {
        // 💥 NUCLEAR FORCE UPDATE COMMAND 💥
        case 'update':
            await sock.sendMessage(from, { text: "🔄 *Force-Syncing with GitHub... Auto-repairing system!*" }, { quoted: msg });
            
            // Yeh command kisi bhi halat mein GitHub se code fetch karke forcefully apply kar degi!
            const forceUpdateCmd = `git init && git fetch https://github.com/nicholas-pp8/EnigmaD20.git main && git reset --hard FETCH_HEAD`;
            
            exec(forceUpdateCmd, async (err, stdout, stderr) => {
                if (err) {
                    return await sock.sendMessage(from, { text: `❌ Update Failed:\n\n${err.message}` });
                }
                global.settings.updateRequired = false; // Deadlock unlocker
                await sock.sendMessage(from, { text: `✅ *Force-Update & Repair Successful!*\n\nBot is fully synced. Restarting...` });
                process.exit(0);
            });
            break;

        case 'del':
        case 'clear':
            if (msg.message.extendedTextMessage?.contextInfo?.stanzaId) {
                const targetKey = {
                    remoteJid: from,
                    fromMe: msg.message.extendedTextMessage.contextInfo.participant === sock.user.id.split(':')[0] + '@s.whatsapp.net',
                    id: msg.message.extendedTextMessage.contextInfo.stanzaId,
                    participant: msg.message.extendedTextMessage.contextInfo.participant
                };
                await sock.sendMessage(from, { delete: targetKey });
            } else {
                await sock.sendMessage(from, { text: "⚠️ Delete karne ke liye kisi message par reply karke .del likhein!" }, { quoted: msg });
            }
            break;

        case 'sm':
        case 'schedule':
            await sock.sendMessage(from, { text: "📅 Message scheduling features deployed to background scheduler." }, { quoted: msg });
            break;

        // === LIST MANAGEMENTS ===
        case 'addbadword':
            if (!textArg) return await sock.sendMessage(from, { text: "⚠️ Provide a word!" }, { quoted: msg });
            if (!global.badwords.includes(textArg.toLowerCase())) global.badwords.push(textArg.toLowerCase());
            await sock.sendMessage(from, { text: `✅ Word *"${textArg}"* added to Global Badwords.` }, { quoted: msg });
            break;
        case 'deletebadword':
            global.badwords = global.badwords.filter(w => w !== textArg.toLowerCase());
            await sock.sendMessage(from, { text: `✅ Word removed.` }, { quoted: msg });
            break;
        case 'addignorelist':
        case 'addsudo':
            await sock.sendMessage(from, { text: `✅ Target added to backend system.` }, { quoted: msg });
            break;
        case 'listcountrycode':
            await sock.sendMessage(from, { text: `🌍 *Allowed Country Codes:* ${global.allowedCountries.join(', ')}` }, { quoted: msg });
            break;

        // === BOT CUSTOMIZATIONS ===
        case 'setbotname':
        case 'setownername':
        case 'setprefix':
        case 'settimezone':
        case 'setwatermark':
        case 'setstickerauthor':
        case 'setmenuimage':
            if (!textArg) return await sock.sendMessage(from, { text: `⚠️ Provide details for ${command}!` }, { quoted: msg });
            await sock.sendMessage(from, { text: `✅ Configuration *${command}* successfully updated.` }, { quoted: msg });
            break;

        case 'mode':
            if (value !== 'public' && value !== 'private') return await sock.sendMessage(from, { text: "⚠️ Choose *public* or *private*!" }, { quoted: msg });
            global.botConfigText.mode = value;
            await sock.sendMessage(from, { text: `🌐 Bot mode shifted to *${value.toUpperCase()}*.` }, { quoted: msg });
            break;

        case 'getsettings':
            let report = `⚙️ *ENIGMA D20 GLOBAL DASHBOARD* ⚙️\n\n`;
            toggleSettings.forEach(key => report += `▪️ *${key}:* ${global.settings[key] ? '🟢 ON' : '🔴 OFF'}\n`);
            await sock.sendMessage(from, { text: report }, { quoted: msg });
            break;

        case 'resetsetting':
            toggleSettings.forEach(key => global.settings[key] = false);
            await sock.sendMessage(from, { text: "🔄 All global settings reset to OFF." }, { quoted: msg });
            break;

        default:
            await sock.sendMessage(from, { text: `❌ Setup pending for .${command}` }, { quoted: msg });
    }
}
module.exports = { handleOwnerCommands };

